# Generated by Django 5.1.2 on 2024-12-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
