# Generated by Django 5.1.2 on 2024-12-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_review", "0002_book_publication_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="publication_date",
        ),
    ]
