# Generated by Django 5.1.2 on 2024-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_review", "0003_remove_book_publication_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
