# Generated by Django 5.1.2 on 2024-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_review", "0004_delete_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="author",
            field=models.CharField(default="Unknown Author", max_length=255),
        ),
    ]
