# Generated by Django 5.1.2 on 2024-12-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_review", "0008_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
