# Generated by Django 5.1.2 on 2024-12-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_review", "0009_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
